# Generated by Django 6.0.2 on 2026-02-06 13:38

import django.db.models.deletion
import django.db.models.functions.text
import profiles.models
import profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True, validators=[profiles.validators.validate_username])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=profiles.models.user_profile_image_path)),
                ('instagram_url', models.URLField(blank=True, validators=[profiles.validators.validate_instagram_url])),
                ('linkedin_url', models.URLField(blank=True, validators=[profiles.validators.validate_linkedin_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='profile_username_idx'), models.Index(fields=['-created_at'], name='profile_created_at_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), condition=models.Q(('username__isnull', False)), name='unique_username_ci')],
            },
        ),
    ]
